### ISSUE TITLE
option to push completed layers even if the overall docker build fails

### ISSUE THREAD

**Issue by TSMMark** [buildkite-plugins/docker-compose-buildkite-plugin#295]
Example of the problem situation: CI dockerfile builds for 30 min, then step 15/20 fails, so the docker build fails, and all the 30 minutes of work is wasted. Subsequent builds will have to repeat the 30 min of work. 

However, many layers of the image were successfully built. It would be great if those layers could be pushed to ECR, for example, so that the next build can reuse the work done already, and download the cached layers, and continue building from there.

Is this possible?

**Comment by toote** [comment]
It is an interesting use case... but I don't see a way to support this in the plugin without complicating the code a lot and possibly breaking existing workflows. As I understand it, we would need to identify the image name of the last intermediate layer successfully built, tag it in some way so that it could be later referenced (like in a cache-from stanza) and then push it.

On the other hand, that could also be achieved by breaking up your Dockerfile so that each intermediate layer was its own image. Which is basically what multi-stage builds are :)

Closing for now as I don't think there is an issue or enhancement on this plugin necessary for that feature.
