### ISSUE TITLE
`push` without using service image

### ISSUE THREAD

**Issue by jlloyd-widen** [buildkite-plugins/docker-compose-buildkite-plugin#313]
The `push` command allows for building an image if a prebuilt image isn't already in place, but when it does this, it uses some sort of cached version ("service image") of the image. I would rather be able to force it to build a new image rather than pulling a service image.

I know I can do with by added a pre-build step, but that's a whole of extra config for no good reason.

More specifically. the push command almost does what I want without a pre-build step. If I don't have the pre-build step, then I get this warning `Skipping build. Using service image ${service_image} from Docker Compose config`. I want it to build the image anyway because otherwise my latest code does not get built into the image.

**Comment by toote** [comment]
Hi @jlloyd-widen! Without a pipeline or example configuration it is more complicated to review exactly the kind of behaviour you mention.

I can think of two scenarios:
1- you need to use the `build` step instead of the `push` one. After all, you actually want to build and push an image. Something like:
```
      - docker-compose:
          build: service
          image-repository: your-registry
          image-name: tag-to-push
```

2- Adding both the `build` and `push` configuration to the very same step. Pre-built step doesn't necessarily mean that it needs to be a separate step (though it could be). Note that if you do this, you may run into #309
