### ISSUE TITLE
cache-from and push fail when specifying docker repository port

### ISSUE THREAD

**Issue by ajoneil** [buildkite-plugins/docker-compose-buildkite-plugin#363]
We're using an internal docker registry for our CI, available at hostname `registry` on the default port 5000.

Specifying the `image-repository` as `registry/myimage` causes docker to assume it's referring to `docker.io/registry/mycoolimage` as the hostname does not contain any `.`, which is not at all desired. Instead using `registry:5000/myimage` corrects this issue, but the additional `:` breaks the tag parsing here:
https://github.com/buildkite-plugins/docker-compose-buildkite-plugin/blob/master/commands/build.sh#L57
and here:
https://github.com/buildkite-plugins/docker-compose-buildkite-plugin/blob/master/commands/push.sh#L25

Giving the errors:
`🚨 cache-from registry:5000/myimage has an invalid tag so it will be ignored`
and
`🚨 specified image to push test-runner:registry:5000/myimage:latest has an invalid tag so it will be ignored`

**Comment by toote** [comment]
@ajoneil that is indeed a very troublesome issue... and it is completely self-inflicted because of using the colon to separate fields ignoring the fact that a registry could indeed have a port :facepalm:

I think I have a way to solve your issue without forcing everyone to update their `cache-from` configurations :thinking: Stay tuned!
