### ISSUE TITLE
Pull down prebuilt images for dependent services

### ISSUE THREAD

**Issue by lox** [buildkite-plugins/docker-compose-buildkite-plugin#96]
Currently only the service that is being run will be checked for prebuilt images. This means that in a situation where you have a system with dependent images, even if you prebuilt them, they will be rebuilt for run.

For example, if you prebuild `nginx` and `php`, and then run `nginx` (which depends on php), `nginx` will get pulled down, but php will be rebuilt. 

Related to #86.

**Comment by chriwu** [comment]
Our docker-compose setup is quite complex, and we are building and running them in various combinations. Being able to prebuild all of em and reuse them when running test containers in subsequent build steps would dramatically reduce our build times. Thank you for looking into this! :-)

**Comment by uriahcarpenter** [comment]
We've published an example Java based project where having the plugin be able to pull pre-built services would be a huge win.

In our case, we run unit tests and building a deployable Docker image in parallel. We then have a suite of integration tests to run on the newly generated Docker image. However, because the integration tests run service `integ`, and not `app`, the Docker image is rebuilt. Functionally, the produced artifact *should* be the same thing... but running the image pushed to the repo would be most ideal.

https://github.com/Widen/gradle-buildkite-docker-compose

For Buildkite personal, look for a support message from @widen.com that has credential info to run the project directly.
